config/routes.rb
Rails.application.routes.draw do 

  devise_for :users,
  controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  get 'home/index'
  get 'items/home_index', to: 'items#home_index'
  get 'items/related_items', to: 'items#related_items'
  post 'stars', to: 'item_stars#create'
  post 'comments', to: 'item_comments#create'
  get 'comments', to: 'item_comments#item_detail_comments'
  get 'stores/home_index', to: 'stores#home_index'
  get 'stores/subcategory_stores', to: 'stores#subcategory_stores'
  get 'items/subcategory_items', to: 'items#subcategory_items'
  get 'store/:id', to: 'stores#show_store'
  get 'stores/my_store', to: 'stores#my_store'
  get 'items/my_items', to: 'items#my_items'
  get 'items/search', to: 'items#search'
  get 'stores/search', to: 'stores#search'
  post 'orders', to: 'orders#create'
  get 'orders/current_orders', to: 'orders#current_orders'
  post 'orders/set_ordered', to: 'orders#set_ordered'
  get 'orders/bought_orders', to: 'orders#bought_orders'
  delete 'orders', to: 'orders#destroy'
  get 'items/store_items', to: 'items#store_items'
  get 'orders/driver_orders', to: 'orders#driver_orders'
  get 'orders/all_orders', to: 'orders#all_orders'
  get 'orders/picked_up', to: 'orders#picked_up'
  get 'orders/delivered', to: 'orders#delivered'
  get 'item', to: 'items#show_item'
  post 'store_analytics/views', to: 'store_analytics#views'
  get 'store_analytics', to: 'store_analytics#show_store_analytics'
  post 'item_analytics/views', to: 'item_analytics#views'
  get 'item_analytics', to: 'item_analytics#item_analytics_index'
  get 'item_analytics/search', to: 'item_analytics#search'
  put 'users/:user_id/stores/:id', to: 'stores#update'
  put 'users/:user_id/stores/:store_id/items/:id', to: 'items#update'
  put 'user/:id/image', to: 'users#update_image'
  put 'user/:id/detail', to: 'users#update_detail'
  patch 'user/:id/update_admin_fields', to: 'users#update_admin_fields', as: 'update_admin_fields'
  get 'user/:id/update_admin_fields', to: 'users#update_admin_fields_form', as: 'update_admin_fields_form'


  root to: 'users#index'

  resources :users do 
    resources :stores do
      resources :store_comments
      resources :store_analytics
      resources :item_analytics
      resources :store_stars
      resources :items do
        resources :item_variants
        resources :tags
        resources :item_comments
        resources :item_stars
        resources :orders do
          resources :order_variants
        end
      end
    end
  end

  resources :cities
  resources :categories do 
    resources :subcategories
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category

  validates :name_en, presence: true
  validates :name_en, uniqueness: true
  validates :name_ku, presence: true
  validates :name_ku, uniqueness: true
  has_many :stores
  has_many :items
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_subcategory, only: %i[show edit update destroy]

  # GET /subcategories or /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1 or /subcategories/1.json
  def show; end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit; end

  # POST /subcategories or /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html do
          redirect_to category_subcategory_url(id: @subcategory), notice: 'Subcategory was successfully created.'
        end
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1 or /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html do
          redirect_to category_subcategory_url(id: @subcategory), notice: 'Subcategory was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1 or /subcategories/1.json
  def destroy
    @subcategory.destroy

    respond_to do |format|
      format.html { redirect_to category_subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subcategory
    @subcategory = Subcategory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subcategory_params
    params.require(:subcategory).permit(:category_id, :name_ku, :name_en)
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_with(model: subcategory, url: url) do |form| %>
  <% if subcategory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
        <% subcategory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id, class: "form-control" %>
  </div>

  <div>
    <%= form.label :name_ku, style: "display: block" %>
    <%= form.text_field :name_ku, class: "form-control" %>
  </div>

  <div>
    <%= form.label :name_en, style: "display: block" %>
    <%= form.text_field :name_en, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Submit", class: "btn btn-primary mt-5" %>
  </div>
<% end %>

app/views/subcategories/_subcategory.html.erb
<div id="<%= dom_id subcategory %>">
  <p>
    <strong>Category:</strong>
    <%= subcategory.category_id %>
  </p>

  <p>
    <strong>Name ku:</strong>
    <%= subcategory.name_ku %>
  </p>

  <p>
    <strong>Name en:</strong>
    <%= subcategory.name_en %>
  </p>

</div>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render "form", subcategory: @subcategory , url: category_subcategory_path%>

<br>

<div>
  <%= link_to "Show this subcategory", category_subcategory(@subcategory) %> |
  <%= link_to "Back to subcategories", category_subcategories_path %>
</div>

app/views/subcategories/index.html.erb
<h1>Subcategories</h1>

<%= link_to "New subcategory", new_category_subcategory_path, class: "btn btn-primary mb-5" %>


<div id="subcategories">
  <% @subcategories.each do |subcategory| %>
    <%= render subcategory %>
    <p>
      <%= link_to "Show this subcategory", category_subcategory_path(id: subcategory) %>
    </p>
  <% end %>
</div>

app/views/subcategories/new.html.erb
<h1>New subcategory</h1>

<%= render "form", subcategory: @subcategory , url: category_subcategories_path%>

<br>

<div>
  <%= link_to "Back to subcategories", category_subcategories_path %>
</div>

app/views/subcategories/show.html.erb
<%= render @subcategory %>

<div>
  <%= link_to "Edit this subcategory", edit_category_subcategory_path(@subcategory) %> |
  <%= link_to "Back to subcategories", category_subcategories_path %>

  <%= button_to "Destroy this subcategory",category_subcategory_path(@subcategory), method: :delete, class: "btn btn-danger mt-5" %>
</div>