config/routes.rb
Rails.application.routes.draw do 

  devise_for :users,
  controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  get 'home/index'
  get 'items/home_index', to: 'items#home_index'
  get 'items/related_items', to: 'items#related_items'
  post 'stars', to: 'item_stars#create'
  post 'comments', to: 'item_comments#create'
  get 'comments', to: 'item_comments#item_detail_comments'
  get 'stores/home_index', to: 'stores#home_index'
  get 'stores/subcategory_stores', to: 'stores#subcategory_stores'
  get 'items/subcategory_items', to: 'items#subcategory_items'
  get 'store/:id', to: 'stores#show_store'
  get 'stores/my_store', to: 'stores#my_store'
  get 'items/my_items', to: 'items#my_items'
  get 'items/search', to: 'items#search'
  get 'stores/search', to: 'stores#search'
  post 'orders', to: 'orders#create'
  get 'orders/current_orders', to: 'orders#current_orders'
  post 'orders/set_ordered', to: 'orders#set_ordered'
  get 'orders/bought_orders', to: 'orders#bought_orders'
  delete 'orders', to: 'orders#destroy'
  get 'items/store_items', to: 'items#store_items'
  get 'orders/driver_orders', to: 'orders#driver_orders'
  get 'orders/all_orders', to: 'orders#all_orders'
  get 'orders/picked_up', to: 'orders#picked_up'
  get 'orders/delivered', to: 'orders#delivered'
  get 'item', to: 'items#show_item'
  post 'store_analytics/views', to: 'store_analytics#views'
  get 'store_analytics', to: 'store_analytics#show_store_analytics'
  post 'item_analytics/views', to: 'item_analytics#views'
  get 'item_analytics', to: 'item_analytics#item_analytics_index'
  get 'item_analytics/search', to: 'item_analytics#search'
  put 'users/:user_id/stores/:id', to: 'stores#update'
  put 'users/:user_id/stores/:store_id/items/:id', to: 'items#update'
  put 'user/:id/image', to: 'users#update_image'
  put 'user/:id/detail', to: 'users#update_detail'
  patch 'user/:id/update_admin_fields', to: 'users#update_admin_fields', as: 'update_admin_fields'
  get 'user/:id/update_admin_fields', to: 'users#update_admin_fields_form', as: 'update_admin_fields_form'


  root to: 'users#index'

  resources :users do 
    resources :stores do
      resources :store_comments
      resources :store_analytics
      resources :item_analytics
      resources :store_stars
      resources :items do
        resources :item_variants
        resources :tags
        resources :item_comments
        resources :item_stars
        resources :orders do
          resources :order_variants
        end
      end
    end
  end

  resources :cities
  resources :categories do 
    resources :subcategories
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images, dependent: :destroy
  has_one :store_stars, dependent: :destroy

  def image_urls
    images.map { |i| Rails.application.routes.url_helpers.url_for(i) }
  end
end

app/controllers/stores_controller.rb
require_relative '../serializers/store_serializer'

class StoresController < ApplicationController
  before_action :authenticate_user!, except: %i[index show show_store home_index subcategory_stores search]
  before_action :set_store, only: %i[show edit update destroy]

  # GET users/:id/stores or users/:id/stores.json
  def index
    @q = Store.where(user_id: params[:user_id]).ransack(params[:q])
    @stores = @q.result(distinct: true).paginate(page: params[:page], per_page: 30)
  end

  # GET users/:id/stores/1 or users/:id/stores/1.json
  def show; end

  def show_store
    @store = Store.find(params[:id])
    render json: StoreSerializer.new(@store).serializable_hash[:data][:attributes]
  end

  # GET users/:id/stores/new
  def new
    @store = Store.new
  end

  # GET users/:id/stores/1/edit
  def edit; end

  # POST users/:id/stores or users/:id/stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html do
          redirect_to user_store_url(user_id: params[:user_id], id: @store.id),
                      notice: 'Store was successfully created.'
        end
        format.json do
          render json: StoreSerializer.new(@store).serializable_hash[:data][:attributes], status: :created
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT users/:id/stores/1 or users/:id/stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to user_store_url(id: @store.id), notice: 'Store was successfully updated.' }
        format.json do
          render json: StoreSerializer.new(@store).serializable_hash[:data][:attributes], status: :created
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE users/:id/stores/1 or users/:id/stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to user_stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def home_index
    @stores = []
    subs = JSON.parse(params[:subcategory_ids])
    count = Store.count
    @stores = if count < 100
                Store.all.with_attached_images
              else
                Store.where(subcategory_id: subs).limit(300).with_attached_images
              end
    options = {}
    options[:is_collection] = true
    json_string = StoreSerializer.new(@stores, options).serializable_hash.to_json
    render json: json_string, status: :ok
  end

  def subcategory_stores
    @stores = []
    subs = params[:subcategory_id]
    @stores = Store.where(subcategory_id: subs).paginate(page: params[:page], per_page: 30).with_attached_images
    options = {}
    options[:is_collection] = true
    json_string = StoreSerializer.new(@stores, options).serializable_hash.to_json
    render json: json_string, status: :ok
  end

  def my_store
    @store = Store.find_by(user_id: params[:user_id])
    render json: StoreSerializer.new(@store).serializable_hash[:data][:attributes]
  end

  def search
    @stores = Store
      .where('(stores.name = ?) or (stores.name like ?) or (stores.name like ?) or (stores.name like ?)',
             params[:name],
             "%#{params[:name]}%",
             "#{params[:name]} %",
             "% #{params[:name]}")
      .paginate(page: params[:page], per_page: 1).with_attached_images

    options = {}
    options[:is_collection] = true
    json_string = StoreSerializer.new(@stores, options).serializable_hash.to_json
    render json: json_string, status: :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def store_params
    params.require(:store).permit(:user_id, :name, :description, :address, :phone, :instagram, :facebook,
                                  :locaation_long, :location_lat, :is_approved,
                                  :category_id, :subcategory_id, :city_id, :images, images: [])
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with model: store, url: path, data:{turbo: false} do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
      <% store.images.each do  |image|%>
      <%= image_tag image, class: "store-image" %>
      <%end %>
  </p>

  <div>
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "form-control" %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id, value: params[:user_id], class: "form-control" %>
  </div>

   <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id, class: "form-control" %>
  </div>

   <div>
    <%= form.label :subcategory_id, style: "display: block" %>
    <%= form.text_field :subcategory_id, class: "form-control" %>
  </div>

   <div>
    <%= form.label :city_id, style: "display: block" %>
    <%= form.text_field :city_id, class: "form-control" %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div>
    <%= form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram, class: "form-control" %>
  </div>

  <div>
    <%= form.label :facebook, style: "display: block" %>
    <%= form.text_field :facebook, class: "form-control" %>
  </div>

  <div>
    <%= form.label :locaation_long, style: "display: block" %>
    <%= form.text_field :locaation_long, class: "form-control" %>
  </div>

  <div>
    <%= form.label :location_lat, style: "display: block" %>
    <%= form.text_field :location_lat, class: "form-control" %>
  </div>

  <div class="d-flex">
    <span> <%= form.check_box :is_approved %></span>
    <span><%= form.label :is_approved, style: "display: block; padding-left: 4px" %></span>
  </div>

  <div>
    <%= form.submit "Submit" , class: "btn btn-primary mt-5" %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">


  <p>
    <strong>User:</strong>
    <%= store.user_id %>
  </p>

   <p>
    <strong>Category:</strong>
    <%= store.category_id %>
  </p>

   <p>
    <strong>Subcategory:</strong>
    <%= store.subcategory_id %>
  </p>

   <p>
    <strong>City:</strong>
    <%= store.city_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= store.description %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= store.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= store.phone %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= store.instagram %>
  </p>

  <p>
    <strong>Facebook:</strong>
    <%= store.facebook %>
  </p>

  <p>
    <strong>Locaation long:</strong>
    <%= store.locaation_long %>
  </p>

  <p>
    <strong>Location lat:</strong>
    <%= store.location_lat %>
  </p>

  <p>
    <strong>Is approved:</strong>
    <%= store.is_approved %>
  </p>

  <%if show_images%>
    <p>
      <% store.images.each do  |image|%>
      <%= image_tag image, class: "store-image" %>
      <%end %>
    </p>
  <%end%>


</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store, path:  user_store_path(id: @store.id)  %>

<br>

<div>
  <%= link_to "Show this store", user_store_path(id: @store.id) %> |
  <%= link_to "Back to stores", user_stores_path %>
</div>

app/views/stores/index.html.erb
<h1>Stores</h1>
<%= link_to "New store", new_user_store_path, class: "btn btn-primary mb-5" %>

<%= render 'shared/search', search_query: :name_cont, placeholder: "Name or user", path: user_stores_url(params[:user_id]) %>
<div id="stores">
  <% @stores.each do |store| %>
    <%= render store , show_images: false%>
    <p>
      <%= link_to "Show this store", user_store_path(id: store.id) %>
    </p>
    <hr/>
  <% end %>
</div>

<div class="d-flex justify-content-center">
    <%= will_paginate @stores, class: "digg_pagination" %>
</div>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store, path: user_stores_path %>

<br>

<div>
  <%= link_to "Back to stores", user_stores_path %>
</div>

app/views/stores/show.html.erb
<%= render @store , show_images: true %>

<div>
  <%= link_to "Edit this store", edit_user_store_path(@store) %> |
  <%= link_to "Back to stores", user_stores_path %>
  <%= button_to "Destroy this store",user_store_path(id:@store ) , method: :delete , class: "btn btn-danger mt-5" %>
</div>