config/routes.rb
Rails.application.routes.draw do 

  devise_for :users,
  controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  get 'home/index'
  get 'items/home_index', to: 'items#home_index'
  get 'items/related_items', to: 'items#related_items'
  post 'stars', to: 'item_stars#create'
  post 'comments', to: 'item_comments#create'
  get 'comments', to: 'item_comments#item_detail_comments'
  get 'stores/home_index', to: 'stores#home_index'
  get 'stores/subcategory_stores', to: 'stores#subcategory_stores'
  get 'items/subcategory_items', to: 'items#subcategory_items'
  get 'store/:id', to: 'stores#show_store'
  get 'stores/my_store', to: 'stores#my_store'
  get 'items/my_items', to: 'items#my_items'
  get 'items/search', to: 'items#search'
  get 'stores/search', to: 'stores#search'
  post 'orders', to: 'orders#create'
  get 'orders/current_orders', to: 'orders#current_orders'
  post 'orders/set_ordered', to: 'orders#set_ordered'
  get 'orders/bought_orders', to: 'orders#bought_orders'
  delete 'orders', to: 'orders#destroy'
  get 'items/store_items', to: 'items#store_items'
  get 'orders/driver_orders', to: 'orders#driver_orders'
  get 'orders/all_orders', to: 'orders#all_orders'
  get 'orders/picked_up', to: 'orders#picked_up'
  get 'orders/delivered', to: 'orders#delivered'
  get 'item', to: 'items#show_item'
  post 'store_analytics/views', to: 'store_analytics#views'
  get 'store_analytics', to: 'store_analytics#show_store_analytics'
  post 'item_analytics/views', to: 'item_analytics#views'
  get 'item_analytics', to: 'item_analytics#item_analytics_index'
  get 'item_analytics/search', to: 'item_analytics#search'
  put 'users/:user_id/stores/:id', to: 'stores#update'
  put 'users/:user_id/stores/:store_id/items/:id', to: 'items#update'
  put 'user/:id/image', to: 'users#update_image'
  put 'user/:id/detail', to: 'users#update_detail'
  patch 'user/:id/update_admin_fields', to: 'users#update_admin_fields', as: 'update_admin_fields'
  get 'user/:id/update_admin_fields', to: 'users#update_admin_fields_form', as: 'update_admin_fields_form'


  root to: 'users#index'

  resources :users do 
    resources :stores do
      resources :store_comments
      resources :store_analytics
      resources :item_analytics
      resources :store_stars
      resources :items do
        resources :item_variants
        resources :tags
        resources :item_comments
        resources :item_stars
        resources :orders do
          resources :order_variants
        end
      end
    end
  end

  resources :cities
  resources :categories do 
    resources :subcategories
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :item
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_tag, only: %i[show edit update destroy]

  # GET /tags or /tags.json
  def index
    @tags = Tag.where(item_id: params[:item_id])
  end

  # GET /tags/1 or /tags/1.json
  def show; end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to user_store_item_tag_url(id: @tag), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to user_store_item_tag_url(id: @tag), notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to user_store_item_tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name, :item_id)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, url: url) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id, class: "form-control", value: params[:item_id]  %>
  </div>

  <div>
    <%= form.submit 'Submit', class: "btn btn-primary mt-5" %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.name %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= tag.item_id %>
  </p>

</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag, url: user_store_item_tag_path %>

<br>

<div>
  <%= link_to "Show this tag",user_store_item_tag_path(@tag)  %> |
  <%= link_to "Back to tags", user_store_item_tags_path %>
</div>

app/views/tags/index.html.erb
<h1>Tags</h1>

<%= link_to "New tag", new_user_store_item_tag_path, class: "btn btn-primary mb-5" %>
<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag",  user_store_item_tag_path(id: tag) %>
    </p>
    <hr/>
  <% end %>
</div>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render "form", tag: @tag, url: user_store_item_tags_path  %>

<br>

<div>
  <%= link_to "Back to tags", user_store_item_tags_path %>
</div>

app/views/tags/show.html.erb
<%= render @tag %>

<div>
  <%= link_to "Edit this tag", edit_user_store_item_tag_path(@tag) %> |
  <%= link_to "Back to tags", user_store_item_tags_path %>

  <%= button_to "Destroy this tag", user_store_item_tag_path(@tag), method: :delete, class: "btn btn-danger mt-5" %>
</div>