config/routes.rb
Rails.application.routes.draw do 

  devise_for :users,
  controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  get 'home/index'
  get 'items/home_index', to: 'items#home_index'
  get 'items/related_items', to: 'items#related_items'
  post 'stars', to: 'item_stars#create'
  post 'comments', to: 'item_comments#create'
  get 'comments', to: 'item_comments#item_detail_comments'
  get 'stores/home_index', to: 'stores#home_index'
  get 'stores/subcategory_stores', to: 'stores#subcategory_stores'
  get 'items/subcategory_items', to: 'items#subcategory_items'
  get 'store/:id', to: 'stores#show_store'
  get 'stores/my_store', to: 'stores#my_store'
  get 'items/my_items', to: 'items#my_items'
  get 'items/search', to: 'items#search'
  get 'stores/search', to: 'stores#search'
  post 'orders', to: 'orders#create'
  get 'orders/current_orders', to: 'orders#current_orders'
  post 'orders/set_ordered', to: 'orders#set_ordered'
  get 'orders/bought_orders', to: 'orders#bought_orders'
  delete 'orders', to: 'orders#destroy'
  get 'items/store_items', to: 'items#store_items'
  get 'orders/driver_orders', to: 'orders#driver_orders'
  get 'orders/all_orders', to: 'orders#all_orders'
  get 'orders/picked_up', to: 'orders#picked_up'
  get 'orders/delivered', to: 'orders#delivered'
  get 'item', to: 'items#show_item'
  post 'store_analytics/views', to: 'store_analytics#views'
  get 'store_analytics', to: 'store_analytics#show_store_analytics'
  post 'item_analytics/views', to: 'item_analytics#views'
  get 'item_analytics', to: 'item_analytics#item_analytics_index'
  get 'item_analytics/search', to: 'item_analytics#search'
  put 'users/:user_id/stores/:id', to: 'stores#update'
  put 'users/:user_id/stores/:store_id/items/:id', to: 'items#update'
  put 'user/:id/image', to: 'users#update_image'
  put 'user/:id/detail', to: 'users#update_detail'
  patch 'user/:id/update_admin_fields', to: 'users#update_admin_fields', as: 'update_admin_fields'
  get 'user/:id/update_admin_fields', to: 'users#update_admin_fields_form', as: 'update_admin_fields_form'


  root to: 'users#index'

  resources :users do 
    resources :stores do
      resources :store_comments
      resources :store_analytics
      resources :item_analytics
      resources :store_stars
      resources :items do
        resources :item_variants
        resources :tags
        resources :item_comments
        resources :item_stars
        resources :orders do
          resources :order_variants
        end
      end
    end
  end

  resources :cities
  resources :categories do 
    resources :subcategories
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/store_analytic.rb
class StoreAnalytic < ApplicationRecord
  belongs_to :store
end

app/controllers/store_analytics_controller.rb
class StoreAnalyticsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_store_analytic, only: %i[show edit update destroy]

  # GET /store_analytics or /store_analytics.json
  def index
    @store_analytics = StoreAnalytic.where(store_id: params[:store_id])
  end

  # GET /store_analytics/1 or /store_analytics/1.json
  def show; end

  def show_store_analytics
    @store_analytic = StoreAnalytic.find_by(store_id: params[:store_id])
    @orders = Order.where(store_id: params[:store_id])
    @store_analytic.total_revenue_usd = @orders.where(currency: 'USD').sum(:total_price)
    @store_analytic.total_revenue_iqd = @orders.where(currency: 'IQD').sum(:total_price)
    @store_analytic.total_item_sales = @orders.sum(:quantity)
    render json: @store_analytic
  end

  # GET /store_analytics/new
  def new
    @store_analytic = StoreAnalytic.new
  end

  # GET /store_analytics/1/edit
  def edit; end

  # POST /store_analytics or /store_analytics.json
  def create
    @store_analytic = StoreAnalytic.new(store_analytic_params)

    respond_to do |format|
      if @store_analytic.save
        format.html do
          redirect_to user_store_store_analytic_url(id: @store_analytic),
                      notice: 'Store analytic was successfully created.'
        end
        format.json { render :show, status: :created, location: @store_analytic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store_analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_analytics/1 or /store_analytics/1.json
  def update
    respond_to do |format|
      if @store_analytic.update(store_analytic_params)
        format.html do
          redirect_to user_store_store_analytic_url(id: @store_analytic),
                      notice: 'Store analytic was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @store_analytic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store_analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_analytics/1 or /store_analytics/1.json
  def destroy
    @store_analytic.destroy

    respond_to do |format|
      format.html { redirect_to user_store_store_analytics_url, notice: 'Store analytic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def views
    @store_analytic = StoreAnalytic.find_by(store_id: params[:store_id])
    if @store_analytic.nil?
      @store_analytic = StoreAnalytic.new(store_id: params[:store_id], store_name: params[:store_name],
                                          lifetime_views: 1)
    else
      @store_analytic.lifetime_views += 1
    end
    @store_analytic.save
    render json: @store_analytic
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store_analytic
    @store_analytic = StoreAnalytic.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def store_analytic_params
    params.require(:store_analytic).permit(:store_id, :store_name, :lifetime_views, :total_stars, :total_reviews,
                                           :total_shares, :total_comments, :total_revenue_usd,
                                           :total_revenue_iqd, :total_item_sales)
  end
end

app/helpers/store_analytics_helper.rb
module StoreAnalyticsHelper
end

app/views/store_analytics/_form.html.erb
<%= form_with(model: store_analytic, url: url) do |form| %>
  <% if store_analytic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store_analytic.errors.count, "error") %> prohibited this store_analytic from being saved:</h2>

      <ul>
        <% store_analytic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :store_id, style: "display: block" %>
    <%= form.text_field :store_id, value: params[:store_id], class: "form-control" %>
  </div>

  <div>
    <%= form.label :store_name, style: "display: block" %>
    <%= form.text_field :store_name, class: "form-control"  %>
  </div>

  <div>
    <%= form.label :lifetime_views, style: "display: block" %>
    <%= form.text_field :lifetime_views, class: "form-control" %>
  </div>

  <div>
    <%= form.label :total_stars, style: "display: block" %>
    <%= form.number_field :total_stars, class: "form-control" %>
  </div>

  <div>
    <%= form.label :total_reviews, style: "display: block" %>
    <%= form.text_field :total_reviews, class: "form-control" %>
  </div>

  <div>
    <%= form.label :total_shares, style: "display: block" %>
    <%= form.text_field :total_shares, class: "form-control" %>
  </div>

  <div>
    <%= form.label :total_comments, style: "display: block" %>
    <%= form.text_field :total_comments, class: "form-control" %>
  </div>

  <div>
    <%= form.label :total_revenue_usd, style: "display: block" %>
    <%= form.text_field :total_revenue_usd, class: "form-control" %>
  </div>

  <div>
    <%= form.label :total_revenue_iqd, style: "display: block" %>
    <%= form.text_field :total_revenue_iqd, class: "form-control" %>
  </div>

  <div>
    <%= form.label :total_item_sales, style: "display: block" %>
    <%= form.text_field :total_item_sales, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Submit" , class: "btn btn-primary mt-5" %>
  </div>
<% end %>

app/views/store_analytics/_store_analytic.html.erb
<div id="<%= dom_id store_analytic %>">
  <p>
    <strong>Store:</strong>
    <%= store_analytic.store_id %>
  </p>

  <p>
    <strong>Store name:</strong>
    <%= store_analytic.store_name %>
  </p>

  <p>
    <strong>Lifetime views:</strong>
    <%= store_analytic.lifetime_views %>
  </p>

  <p>
    <strong>Total stars:</strong>
    <%= store_analytic.total_stars %>
  </p>

  <p>
    <strong>Total reviews:</strong>
    <%= store_analytic.total_reviews %>
  </p>

  <p>
    <strong>Total shares:</strong>
    <%= store_analytic.total_shares %>
  </p>

  <p>
    <strong>Total comments:</strong>
    <%= store_analytic.total_comments %>
  </p>

  <p>
    <strong>Total revenue usd:</strong>
    <%= store_analytic.total_revenue_usd %>
  </p>

  <p>
    <strong>Total revenue iqd:</strong>
    <%= store_analytic.total_revenue_iqd %>
  </p>

  <p>
    <strong>Total item sales:</strong>
    <%= store_analytic.total_item_sales %>
  </p>

</div>

app/views/store_analytics/edit.html.erb
<h1>Editing store analytic</h1>

<%= render "form", store_analytic: @store_analytic, url: user_store_store_analytic_url %>

<br>

<div>
  <%= link_to "Show this store analytic", user_store_store_analytic_path(id: @store_analytic) %> |
  <%= link_to "Back to store analytics", user_store_store_analytics_path %>
</div>

app/views/store_analytics/index.html.erb
<h1>Store analytics</h1>
<%= link_to "New store analytic", new_user_store_store_analytic_path, class: "btn btn-primary mb-5" %>

<div id="store_analytics">
  <% @store_analytics.each do |store_analytic| %>
    <%= render store_analytic %>
    <p>
      <%= link_to "Show this store analytic", user_store_store_analytic_path(id: store_analytic) %>
    </p>
  <% end %>
</div>

app/views/store_analytics/new.html.erb
<h1>New store analytic</h1>

<%= render "form", store_analytic: @store_analytic, url: user_store_store_analytics_url %>

<br>

<div>
  <%= link_to "Back to store analytics", user_store_store_analytics_path %>
</div>

app/views/store_analytics/show.html.erb
<%= render @store_analytic %>

<div>
  <%= link_to "Edit this store analytic", edit_user_store_store_analytic_path(@store_analytic) %> |
  <%= link_to "Back to store analytics", user_store_store_analytics_path %>

  <%= button_to "Destroy this store analytic", user_store_store_analytic_path(id: @store_analytic), method: :delete, class: "btn btn-danger mt-5" %>
</div>